name: Scrape Train Departures

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.18.1 pytz==2024.1 webdriver_manager==4.0.1
        
    - name: Run scraper
      run: |
        python scraper.py
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add public/data/departures.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update departure times" && git push) 